### PR TITLE
Disable file type check validation for File Manager

### LINKED ISSUE #676: File Manager: disable file type validation check
### Describe the request
Disable file type validation checks completely.
All file types should be allowed.

### PR DESCRIPTION
**Pull request by skrolikowski**
### What does this implement or fix?
This update disables file type validation check within File Manager.
File Manager will now allow all file types to be uploaded.

### Does this close any currently open issues?
- fixes [fusioncms/fusioncms#676](https://github.com/fusioncms/fusioncms/issues/676)

- [x] All javascript/scss resources are compiled for production

### CODE REVIEW

**Comment by huiyang** [comment]
Why is the file type validation is removed instead of fixed (the error which stop file upload all the time) ?

I found that this issue is caused by getting setting with wrong path:

Current Code (not working):
``` javascript
let acceptedTypes = this.getSetting('files.accepted_files')
let maxSize       = this.getSetting('files.file_size_upload_limit')
```

Working (I not sure whether the structure is correct, but using this way will able to get the value)
``` js
let acceptedTypes = this.getSetting('accepted_files')
let maxSize       = this.getSetting('file_size_upload_limit')
```

**Comment by huiyang** [comment]
there is another solution: changing resources/js/store/settings.js
"setSettings" method to:

``` js
setSettings (state, payload) {
     let settings = {}

     _.each(payload, (item) => {
          _.each(item.settings, ((value, setting) => {
               settings[item.handle + '.' + setting] = value
          }))
     })
            
     state.settings = settings
},
```

 (to me, this solution is better, but not sure if it will affect other components? haven't have time to have a detail check)

**Comment by kaidesu** [comment]
Doesn't make sense to limit the type of files that can be uploaded to the file manager directly. Instead, this will be a setting you can configure on the file fieldtype directly.

**Comment by huiyang** [comment]
Oh I see, then make sense

**Pull request merged**
